[project]
name = "wedjat-rknn"
version = "0.1.0"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "datasets>=5.0.1",
    "fast-histogram>=0.11",
    "numpy>=2.0",
    "onnx>=1.16",
    "onnxruntime>=1.22.0",
    "opencv-python>=4.8",
    "pandas>=3.0.5",
    "pillow>=12.3.0",
    "prettytable>=3.18.0",
    "protobuf>=4.21.6,<=6.33.6",
    "psutil>=5.9.0",
    "ruamel-yaml>=0.17.21",
    "safetensors>=0.8.0",
    "scipy>=1.12.0",
    "sentencepiece>=0.2.2",
    "tabulate>=0.10.0",
    "torch>=2.2",
    "tqdm>=4.64.1",
    "transformers==4.51.3",
    "rknn3-toolkit",
    "rasterio>=1.5.1",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[tool.uv.sources]
rknn3-toolkit = { path = "rknn3_toolkit-1.1.0-cp312-cp312-manylinux2014_x86_64.whl" }

[tool.pyright]
extraPaths = [
    "src/",
]

# [build-system]
# requires = ["hatchling"]
# build-backend = "hatchling.build"
